# Site wide configuration

title: Ying Zheng
locale: en_US
description: “Happiness is not to be achieved at the command of emotional whims. Happiness is not the satisfaction of whatever irrational wishes you might blindly attempt to indulge. Happiness is a state of non-contradictory joy—a joy without penalty or guilt, a joy that does not clash with any of your values and does not work for your own destruction, not the joy of escaping from your mind, but of using your mind's fullest power, not the joy of faking reality, but of achieving values that are real, not the joy of a drunkard, but of a producer. Happiness is possible only to a rational man, the man who desires nothing but rational goals, seeks nothing but rational values and finds his joy in nothing but rational actions.” ― Ayn Rand, Atlas Shrugged
logo: site-logo.jpg
search: true
url: https://martinyingzheng.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Ying Zheng
  avatar: bio-photo.jpg
  email: you@email.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
